# Generated by Django 5.0.6 on 2024-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_word_audio', models.FileField(blank=True, null=True, upload_to='health_audio/')),
                ('health_word_text', models.CharField(max_length=100)),
                ('health_contact1', models.CharField(max_length=15)),
                ('health_contact2', models.CharField(max_length=15)),
                ('health_contact3', models.CharField(max_length=15)),
                ('ambulance_contact', models.CharField(max_length=15)),
                ('family_doctor_contact', models.CharField(max_length=15)),
                ('nearest_hospital_location', models.CharField(max_length=255)),
                ('threat_word_audio', models.FileField(blank=True, null=True, upload_to='threat_audio/')),
                ('threat_word_text', models.CharField(max_length=100)),
                ('threat_contact1', models.CharField(max_length=15)),
                ('threat_contact2', models.CharField(max_length=15)),
                ('threat_contact3', models.CharField(max_length=15)),
                ('nearest_police_station_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('safety_status', models.BooleanField(default=True)),
                ('safety_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
