# Generated by Django 5.0.6 on 2024-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyprofile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyprofile',
            name='ambulance_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='family_doctor_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='health_contact1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='health_contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='health_contact3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='nearest_hospital_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='nearest_police_station_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='threat_contact1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='threat_contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safetyprofile',
            name='threat_contact3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
